name: Local Config
version: 1.0.0
schema: v1
models:
  # - name: qwen2.5-coder:14b
  #   model: qwen2.5-coder:14b
  #   apiBase: http://192.168.0.236:11434
  #   provider: ollama
  # - name: gpt-oss:20b
  #   model: gpt-oss:20b
  #   apiBase: http://192.168.0.236:11434
  #   provider: ollama
  # - name: dc16
  #   model: dc16
  #   apiBase: http://192.168.0.236:11434
  #   provider: ollama
  # - name: dci16
  #   model: dci16
  #   apiBase: http://192.168.0.236:11434
  #   provider: ollama
  - name: qwen3-coder
    model: qwen3-coder
    apiBase: http://192.168.0.236:11434
    provider: ollama
  - name: qwen2.5-coder:1.5b
    model: qwen2.5-coder:1.5b
    apiBase: http://localhost:11434
    provider: ollama
    roles:
      - autocomplete


